#!/usr/bin/env bash
# https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR && ./java-runtime/bin/java -jar ./resources/mardek.jar enable-logging $@
