#version 450

layout(set = 0, binding = 0) writeonly buffer OutputBuffer {
	uint outputBuffer[];
};

layout(set = 0, binding = 1) uniform sampler2D inputTexture;

layout(push_constant) uniform PushConstants {
	uvec2 bufferSize;
	uvec2 usedInputOffset;
	uvec2 usedInputSize;
	uvec2 fullInputSize;
	uint bufferOffset;
	uint pushFilterSize;
	uint sectionLength;
};

#include "../decode.glsl"
#include "./encode.glsl"
#include "./filter.glsl"

uint fetchColor(uint x) {
	vec2 usedFactor = vec2(usedInputSize) / vec2(fullInputSize);
	float normalizedX = (x + 0.5) / bufferSize.x * usedFactor.x;
	uint y = 64 * gl_WorkGroupID.x + gl_LocalInvocationIndex;
	float normalizedY = (y + 0.5) / bufferSize.y * usedFactor.y;
	return encodeColor(texture(inputTexture, vec2(normalizedX, normalizedY)));
}

uint getInputSize() {
	//return usedInputOffset.x + usedInputSize.x;
	return bufferSize.x;
}

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

#define supportFilterSize(supportedFilterSize, filterFunction, unroll) if (pushFilterSize == supportedFilterSize) {\
		initializeFilterWindow(baseX, supportedFilterSize, unroll);\
		uint limit = min(getInputSize(), baseX + sectionLength);\
		for (uint x = baseX; x < limit; x += unroll) {\
			applyFilter(x, 1, supportedFilterSize, filterFunction, unroll);\
		}\
	}

void main() {
	uint y = usedInputOffset.y + 64 * gl_WorkGroupID.x + gl_LocalInvocationIndex;
	if (y >= usedInputOffset.y + bufferSize.y) return;

	int baseX = int(usedInputOffset.x) + int(sectionLength * gl_WorkGroupID.y);
	if (baseX >= usedInputOffset.x + bufferSize.x) return;

	supportFilterSize(0, applySingleFilter0, DEFAULT_UNROLL);
	supportFilterSize(1, applySingleFilter1, DEFAULT_UNROLL);
	supportFilterSize(3, applySingleFilter3, DEFAULT_UNROLL);
	supportFilterSize(4, applySingleFilter4, DEFAULT_UNROLL);
	supportFilterSize(9, applySingleFilter9, DEFAULT_UNROLL);
	supportFilterSize(19, applySingleFilter19, DEFAULT_UNROLL);
}
