package com.github.knokko.bitser.io;

import com.github.knokko.bitser.RecursionNode;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Arrays;

/**
 * A subclass of {@link BitOutputStream} that is used to debug bitser. Just like {@link BitOutputStream}, you can use it
 * to write bits to an {@link OutputStream}. But, whenever it writes a bit, it prints some additional information to
 * a {@link PrintWriter} that explains what that bit was used for. All printed messages should be equivalent to the
 * messages generated by {@link DebugBitInputStream}, so a diff viewer can be used to check for discrepancies.
 */
public class DebugBitOutputStream extends BitOutputStream {

	private final PrintWriter writer;
	private final boolean aggressiveFlush;

	/**
	 * Constructs a new {@link DebugBitOutputStream}
	 * @param byteStream The {@link OutputStream} to which the bits will be written
	 * @param writer The {@link PrintWriter} to which the debug information should be printed
	 * @param aggressiveFlush Whether the constructed {@link DebugBitInputStream} should call
	 *                        {@link PrintWriter#flush()} after every <b>print</b> or <b>println</b>. Doing this is
	 *                        convenient when the serializer crashes, but is very expensive on big structs.
	 */
	public DebugBitOutputStream(OutputStream byteStream, PrintWriter writer, boolean aggressiveFlush) {
		super(byteStream);
		this.writer = writer;
		this.aggressiveFlush = aggressiveFlush;
	}

	@Override
	public void write(boolean bit) throws IOException {
		super.write(bit);
		writer.print(bit ? '1' : '0');
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void write(int value, int numBits) throws IOException {
		super.write(value, numBits);
		for (int bit = 0; bit < numBits; bit++) writer.print((value & (1 << bit)) != 0 ? '1' : '0');
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void write(byte[] bytes) throws IOException {
		super.write(bytes);
		writer.print(Arrays.toString(bytes));
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void pushContext(RecursionNode context, String fieldName) {
		super.pushContext(context, fieldName);
		writer.println("begin " + context.generateTrace(fieldName));
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void popContext(RecursionNode context, String fieldName) {
		super.popContext(context, fieldName);
		writer.println("end " + context.generateTrace(fieldName));
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void prepareProperty(String fieldName) {
		super.prepareProperty(fieldName);
		writer.print(fieldName + ": ");
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void finishProperty() {
		super.finishProperty();
		writer.println();
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void finish() throws IOException {
		super.finish();
		writer.println("---------------------------------------------------------------------------------------------");
		writer.flush();
	}

	@Override
	public void setMarker(String marker) {
		writer.println();
		writer.println("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< " + marker + " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		writer.println();
		if (aggressiveFlush) writer.flush();
	}
}
