package com.github.knokko.bitser.io;

import com.github.knokko.bitser.RecursionNode;

import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.Arrays;

/**
 * A subclass of {@link BitInputStream} that is used to debug bitser. Just like {@link BitInputStream}, you can use it
 * to read bits from an {@link InputStream}. But, whenever it reads a bit, it prints some additional information to
 * a {@link PrintWriter} that explains what that bit was used for. All printed messages should be equivalent to the
 * messages generated by {@link DebugBitOutputStream}, so a diff viewer can be used to check for discrepancies.
 */
public class DebugBitInputStream extends BitInputStream {

	private final PrintWriter writer;
	private final boolean aggressiveFlush;

	/**
	 * Constructs a new {@link DebugBitInputStream}
	 * @param byteStream The {@link InputStream} from which the bits should be read
	 * @param writer The {@link PrintWriter} to which the debug information should be printed
	 * @param aggressiveFlush Whether the constructed {@link DebugBitInputStream} should call
	 *                        {@link PrintWriter#flush()} after every <b>print</b> or <b>println</b>. Doing this is
	 *                        convenient when the deserializer crashes, but is very expensive on big structs.
	 */
	public DebugBitInputStream(InputStream byteStream, PrintWriter writer, boolean aggressiveFlush) {
		super(byteStream);
		this.writer = writer;
		this.aggressiveFlush = aggressiveFlush;
	}

	@Override
	public boolean read() throws IOException {
		boolean result = super.read();
		writer.print(result ? '1' : '0');
		return result;
	}

	@Override
	public int read(int numBits) throws IOException {
		int result = super.read(numBits);
		for (int bit = 0; bit < numBits; bit++) writer.print((result & (1 << bit)) != 0 ? '1' : '0');
		return result;
	}

	@Override
	public void read(byte[] destination) throws IOException {
		super.read(destination);
		writer.print(Arrays.toString(destination));
	}

	@Override
	public void pushContext(RecursionNode context, String fieldName) {
		super.pushContext(context, fieldName);
		writer.println("begin " + context.generateTrace(fieldName));
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void popContext(RecursionNode context, String fieldName) {
		super.popContext(context, fieldName);
		writer.println("end " + context.generateTrace(fieldName));
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void prepareProperty(String fieldName) {
		super.prepareProperty(fieldName);
		writer.print(fieldName + ": ");
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void finishProperty() {
		super.finishProperty();
		writer.println();
		if (aggressiveFlush) writer.flush();
	}

	@Override
	public void close() throws IOException {
		super.close();
		writer.println("---------------------------------------------------------------------------------------------");
		writer.flush();
	}

	@Override
	public void setMarker(String marker) {
		writer.println();
		writer.println("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< " + marker + " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		writer.println();
		if (aggressiveFlush) writer.flush();
	}
}
