#!/usr/bin/env bash
# https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
"$SCRIPT_DIR/bin/java" -XstartOnFirstThread -jar "$SCRIPT_DIR/mardek.jar" $@