name: Testing on Linux

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y vulkan-validationlayers
      - run: sudo apt install -y mesa-vulkan-drivers
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test
      - run: ./gradlew proguard
      - run: jlink --module-path "%JAVA_HOME%/jmods" --add-modules java.base,jdk.unsupported --output ./game/build/libs/jre
      - run: cp ./build-helper/mardek ./game/build/libs/jre/mardek
      - run: cp ./game/build/libs/mardek.jar ./game/build/libs/jre/mardek.jar
      - run: ./game/build/libs/jre/mardek self-test1
      - uses: actions/upload-artifact@v4
        with:
          name: mardek-linux
          path: ./game/build/libs/jre/
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew proguard
      - run: jlink --module-path "%JAVA_HOME%/jmods" --add-modules java.base,jdk.unsupported --output ./game/build/libs/jre
      # mardek.exe was generated by https://github.com/l-urk/Bat-To-Exe-Converter-64-Bit/releases
      # it's currently commented out due to MS Defender issues: https://github.com/LWJGL/lwjgl3/issues/1005
      #- run: cp ./build-helper/mardek.exe ./game/build/libs/jre/mardek.exe
      - run: cp ./build-helper/mardek.bat ./game/build/libs/jre/mardek.bat
      - run: cp ./game/build/libs/mardek.jar ./game/build/libs/jre/mardek.jar
      - run: ./game/build/libs/jre/mardek.bat self-test1
      - uses: actions/upload-artifact@v4
        with:
          name: mardek-windows
          path: ./game/build/libs/jre/
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew proguard
      - run: jlink --module-path "%JAVA_HOME%/jmods" --add-modules java.base,jdk.unsupported --output ./game/build/libs/jre
      - run: cp ./build-helper/mardek-mac ./game/build/libs/jre/mardek
      - run: cp ./game/build/libs/mardek.jar ./game/build/libs/jre/mardek.jar
      - run: ./game/build/libs/jre/mardek self-test1
      - uses: actions/upload-artifact@v4
        with:
          name: mardek-mac
          path: ./game/build/libs/jre/
  self-test-ubuntu:
    runs-on: ubuntu-latest
    needs: build-and-test-ubuntu
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mardek-linux
          path: ./game
      # For some reason, the execute permission is lost in download-artifact,
      # but not when I download it from my browser on an Ubuntu machine
      - run: chmod 777 ./game/mardek
      - run: chmod 777 ./game/bin/java
      - run: ./game/mardek self-test1
  self-test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mardek-windows
          path: ./game
      - run: ./game/mardek.bat self-test1
  self-test-mac:
    runs-on: macos-latest
    needs: build-mac
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mardek-mac
          path: ./game
      # Just like with Ubuntu, execute permissions are lost in the download
      - run: chmod 777 ./game/mardek
      - run: chmod 777 ./game/bin/java
      - run: ./game/mardek self-test1
